# Generated by Django 5.2.1 on 2025-06-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiqueitem',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.artist'),
        ),
    ]
